version: "3.8"

services:
  backend:
    build: ./backend
    expose:
      - "8000"
    env_file:
      - ./backend/.env
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro

  frontend:
    build: ./frontend
    expose:
      - "3000"
    env_file:
      - ./frontend/.env

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - backend
      - frontend

volumes:
  letsencrypt:
    external: true
